create table if not exists public.strategy_control (
  id bigint generated by default as identity primary key,
  strategy_name text not null unique,
  enabled boolean not null default true,
  mode text not null default 'paper' check (mode in ('paper', 'live', 'off')),
  max_position double precision not null default 0.20,
  last_updated timestamptz not null default now()
);

insert into public.strategy_control (strategy_name, enabled, mode, max_position)
values ('coinbase_v2', true, 'paper', 0.20)
on conflict (strategy_name) do update
set enabled = excluded.enabled,
    mode = excluded.mode,
    max_position = excluded.max_position,
    last_updated = now();
